language: python
python:
    - '2.6'
    - '2.7'

install:
  - pip install pep8 pyflakes
  - pip install Twisted
  - pip install -r requirements.txt
script:
  - pep8 --exclude='_thrift' scrivener
  - find scrivener -not -path '*/_thrift*' -name '*.py' | xargs pyflakes
  - trial scrivener
